import type { Metadata } from "next";

import Aside from "@/components/aside";
import Header from "@/components/header";
import Subhedaer from "@/components/header/subheader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <Aside />
      <main className="flex flex-auto flex-col transition-all duration-300 ease-in-out md:pl-[20rem]">
        <Header />
        <Subhedaer />
        {children}
      </main>
    </div>
  );
}
